/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdmindashboardRouteImport } from './routes/admindashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as CertificateIdRouteImport } from './routes/certificate.$id'
import { Route as AuthenticatedProjectProjectIdRouteImport } from './routes/_authenticated/project.$projectId'
import { Route as AuthenticatedProjectProjectIdIndexRouteImport } from './routes/_authenticated/project.$projectId.index'
import { Route as AuthenticatedProjectProjectIdBulkPreviewRouteImport } from './routes/_authenticated/project.$projectId.bulk-preview'
import { Route as AuthenticatedProjectProjectIdTemplatesRouteImport } from './routes/_authenticated/project.$projectId.templates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmindashboardRoute = AdmindashboardRouteImport.update({
  id: '/admindashboard',
  path: '/admindashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CertificateIdRoute = CertificateIdRouteImport.update({
  id: '/certificate/$id',
  path: '/certificate/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectProjectIdRoute =
  AuthenticatedProjectProjectIdRouteImport.update({
    id: '/project/$projectId',
    path: '/project/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectProjectIdIndexRoute =
  AuthenticatedProjectProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectProjectIdRoute,
  } as any)
const AuthenticatedProjectProjectIdBulkPreviewRoute =
  AuthenticatedProjectProjectIdBulkPreviewRouteImport.update({
    id: '/bulk-preview',
    path: '/bulk-preview',
    getParentRoute: () => AuthenticatedProjectProjectIdRoute,
  } as any)
const AuthenticatedProjectProjectIdTemplatesRoute =
  AuthenticatedProjectProjectIdTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedProjectProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admindashboard': typeof AdmindashboardRoute
  '/auth': typeof AuthRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/certificate/$id': typeof CertificateIdRoute
  '/project/$projectId': typeof AuthenticatedProjectProjectIdRouteWithChildren
  '/project/$projectId/bulk-preview': typeof AuthenticatedProjectProjectIdBulkPreviewRoute
  '/project/$projectId/templates': typeof AuthenticatedProjectProjectIdTemplatesRoute
  '/project/$projectId/': typeof AuthenticatedProjectProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admindashboard': typeof AdmindashboardRoute
  '/auth': typeof AuthRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/certificate/$id': typeof CertificateIdRoute
  '/project/$projectId/bulk-preview': typeof AuthenticatedProjectProjectIdBulkPreviewRoute
  '/project/$projectId/templates': typeof AuthenticatedProjectProjectIdTemplatesRoute
  '/project/$projectId': typeof AuthenticatedProjectProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admindashboard': typeof AdmindashboardRoute
  '/auth': typeof AuthRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/certificate/$id': typeof CertificateIdRoute
  '/_authenticated/project/$projectId': typeof AuthenticatedProjectProjectIdRouteWithChildren
  '/_authenticated/project/$projectId/bulk-preview': typeof AuthenticatedProjectProjectIdBulkPreviewRoute
  '/_authenticated/project/$projectId/templates': typeof AuthenticatedProjectProjectIdTemplatesRoute
  '/_authenticated/project/$projectId/': typeof AuthenticatedProjectProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admindashboard'
    | '/auth'
    | '/verify'
    | '/admin'
    | '/certificate/$id'
    | '/project/$projectId'
    | '/project/$projectId/bulk-preview'
    | '/project/$projectId/templates'
    | '/project/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admindashboard'
    | '/auth'
    | '/verify'
    | '/admin'
    | '/certificate/$id'
    | '/project/$projectId/bulk-preview'
    | '/project/$projectId/templates'
    | '/project/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admindashboard'
    | '/auth'
    | '/verify'
    | '/_authenticated/admin'
    | '/certificate/$id'
    | '/_authenticated/project/$projectId'
    | '/_authenticated/project/$projectId/bulk-preview'
    | '/_authenticated/project/$projectId/templates'
    | '/_authenticated/project/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdmindashboardRoute: typeof AdmindashboardRoute
  AuthRoute: typeof AuthRoute
  VerifyRoute: typeof VerifyRoute
  CertificateIdRoute: typeof CertificateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admindashboard': {
      id: '/admindashboard'
      path: '/admindashboard'
      fullPath: '/admindashboard'
      preLoaderRoute: typeof AdmindashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/certificate/$id': {
      id: '/certificate/$id'
      path: '/certificate/$id'
      fullPath: '/certificate/$id'
      preLoaderRoute: typeof CertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/project/$projectId': {
      id: '/_authenticated/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/project/$projectId/': {
      id: '/_authenticated/project/$projectId/'
      path: '/'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectProjectIdRoute
    }
    '/_authenticated/project/$projectId/bulk-preview': {
      id: '/_authenticated/project/$projectId/bulk-preview'
      path: '/bulk-preview'
      fullPath: '/project/$projectId/bulk-preview'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdBulkPreviewRouteImport
      parentRoute: typeof AuthenticatedProjectProjectIdRoute
    }
    '/_authenticated/project/$projectId/templates': {
      id: '/_authenticated/project/$projectId/templates'
      path: '/templates'
      fullPath: '/project/$projectId/templates'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdTemplatesRouteImport
      parentRoute: typeof AuthenticatedProjectProjectIdRoute
    }
  }
}

interface AuthenticatedProjectProjectIdRouteChildren {
  AuthenticatedProjectProjectIdBulkPreviewRoute: typeof AuthenticatedProjectProjectIdBulkPreviewRoute
  AuthenticatedProjectProjectIdTemplatesRoute: typeof AuthenticatedProjectProjectIdTemplatesRoute
  AuthenticatedProjectProjectIdIndexRoute: typeof AuthenticatedProjectProjectIdIndexRoute
}

const AuthenticatedProjectProjectIdRouteChildren: AuthenticatedProjectProjectIdRouteChildren =
  {
    AuthenticatedProjectProjectIdBulkPreviewRoute:
      AuthenticatedProjectProjectIdBulkPreviewRoute,
    AuthenticatedProjectProjectIdTemplatesRoute:
      AuthenticatedProjectProjectIdTemplatesRoute,
    AuthenticatedProjectProjectIdIndexRoute:
      AuthenticatedProjectProjectIdIndexRoute,
  }

const AuthenticatedProjectProjectIdRouteWithChildren =
  AuthenticatedProjectProjectIdRoute._addFileChildren(
    AuthenticatedProjectProjectIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedProjectProjectIdRoute: typeof AuthenticatedProjectProjectIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedProjectProjectIdRoute:
    AuthenticatedProjectProjectIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdmindashboardRoute: AdmindashboardRoute,
  AuthRoute: AuthRoute,
  VerifyRoute: VerifyRoute,
  CertificateIdRoute: CertificateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
