/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdmindashboardRouteImport } from './routes/admindashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as CertificateIdRouteImport } from './routes/certificate.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmindashboardRoute = AdmindashboardRouteImport.update({
  id: '/admindashboard',
  path: '/admindashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CertificateIdRoute = CertificateIdRouteImport.update({
  id: '/certificate/$id',
  path: '/certificate/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admindashboard': typeof AdmindashboardRoute
  '/auth': typeof AuthRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/certificate/$id': typeof CertificateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admindashboard': typeof AdmindashboardRoute
  '/auth': typeof AuthRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/certificate/$id': typeof CertificateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admindashboard': typeof AdmindashboardRoute
  '/auth': typeof AuthRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/certificate/$id': typeof CertificateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admindashboard'
    | '/auth'
    | '/verify'
    | '/admin'
    | '/certificate/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admindashboard'
    | '/auth'
    | '/verify'
    | '/admin'
    | '/certificate/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admindashboard'
    | '/auth'
    | '/verify'
    | '/_authenticated/admin'
    | '/certificate/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdmindashboardRoute: typeof AdmindashboardRoute
  AuthRoute: typeof AuthRoute
  VerifyRoute: typeof VerifyRoute
  CertificateIdRoute: typeof CertificateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admindashboard': {
      id: '/admindashboard'
      path: '/admindashboard'
      fullPath: '/admindashboard'
      preLoaderRoute: typeof AdmindashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/certificate/$id': {
      id: '/certificate/$id'
      path: '/certificate/$id'
      fullPath: '/certificate/$id'
      preLoaderRoute: typeof CertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdmindashboardRoute: AdmindashboardRoute,
  AuthRoute: AuthRoute,
  VerifyRoute: VerifyRoute,
  CertificateIdRoute: CertificateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
